name: CI - Cháº¡y test

# Dieu kien de chay pipeline
# don gian: trigger chay test khi push code len github
# tao pull request  -> trigger pipeline
# merge pull request -> trigger pipeline

on:
  push:
    branches: [main, master]

jobs:
  test: #define step test
    # Chon moi truong de chay step test
    # ubuntu-latest: chay tren he dieu hanh linux
    # windows-latest: chay tren he dieu hanh windows
    # macos-latest: chay tren he dieu hanh macos
    runs-on: ubuntu-latest
    steps:
      # B1: clone source code tu github
      - name: Checkout code
        uses: actions/checkout@v4

      # B2: Thiet lap moi truong nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm' # cache giup tang toc do build playwright

      # B3: Cat dat cac thu vien co trong source code playwright
      - name: Install dependencies
        run: npm install

      # B4: Cai browser co san cua playwright
      # with-deps: cai dat them cac thu vien phu thuoc cua browser
      - name: Install playwright browsers
        run: npx playwright install --with-deps

      # B5: Chay test
      - name: Run playwright test
        run: npx playwright test 
